### ISSUE TITLE
Feature Suggestion: Total spots available graph

### ISSUE THREAD

**Issue by isConic** [millkhan/utdgarages#1]
I really love this site. Id like to request a third graph that tells us the total spots available across all structures. I think that would be a nice addition that tells the whole parking story on campus.

**Comment by millkhan** [comment]
This is something I'm not opposed to adding.

What are your thoughts on having a separate page (something like https://utdgarages.com/master-graph) and an additional button at the footer that links to it like this: 

![new-footer](https://user-images.githubusercontent.com/87798236/191126758-9392484a-82d4-4eaf-a675-7538e49cbe41.png)

This should prevent cluttering of the main page and allow users to access the master graph on a separate page if they want to.

**Comment by isConic** [comment]
@millkhan  I'd be a fan of that. 
I was trying to figure out how to visually distinguish it from the other graphs if they were on the same page. (so as to avoid confusion or mixing up graphs).

I think a separate page would be the best solution to this problem

**Comment by millkhan** [comment]
Added in release [v1.1.0 ](https://github.com/millkhan/utdgarages/releases/tag/v1.1.0)
