### ISSUE TITLE
Feature Suggestion: Mini-map per parking structure

### ISSUE THREAD

**Issue by isConic** [millkhan/utdgarages#2]
### Minimap:
For each parking structure, display a google map zoomed in on the parking structure on the far right side of the line chart. It's not blueprints or anything about the parking structure, it just tells us where it is. 

![image](https://user-images.githubusercontent.com/48657113/191109341-5efacf97-39b7-4369-9db8-54c45da2debe.png)

### What problem this solves: 
- Helps us remember which building is which parking structure. 
- Helps us quickly find the graph we're looking for (the `PS1` and `PS2` are a bit small atm). Might be easier to find the chart we're looking for by it's shape on the map, rather than PS1, or PS2.   

### Specification: 
- The minimaps should not be interactive or zoom. It can even be just a cropped image of a map, as long as it tells us roughly what that is. 
- Can be styled however. I used [this](https://snazzymaps.com/) sometimes, or mapbox stuff.  
- The way I laid it out in the diagram above, you might have room to display extra meta-data or future features below the map.

**Comment by isConic** [comment]
So maybe something like this? 

![image](https://user-images.githubusercontent.com/48657113/191115867-a743ddf7-4996-4c9d-b452-c872e0119ff0.png)

The style for it is this: 
https://snazzymaps.com/style/27760/urban-study

**Comment by millkhan** [comment]
At the current layout of the main page, I don't see any feasible way to put the images into each garage section without substantially squishing the tables or charts (especially on smaller width devices).

It may be possible on wider displays, but it would look awkward on most devices.

Additionally, the main page's focus should solely be on quickly providing the data - adding the map images would shift the focus.

**Comment by isConic** [comment]
I see. I had not considered smaller/mobile displays in my suggestion. I was hoping that there'd be an easy way to remind people which parking structure is which and,at a quick glance, determine which parking lot each graph belongs to. I guess it wouldn't be too much of a stretch to assume that users know the basics about what the parking structures are before looking for data on it.
